# Generated by Django 3.2.3 on 2021-07-05 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de Lançamento')),
                ('amount_track', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantidade de Faixas')),
                ('cover', models.ImageField(upload_to='', verbose_name='Capa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Última Modificação')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Telefone')),
                ('kind', models.CharField(choices=[('C', 'Celular'), ('F', 'Fixo')], max_length=1, verbose_name='Tipo')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='WhatsApp?')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='MusicStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Última Modificação')),
            ],
            options={
                'verbose_name': 'Estilo Musical',
                'verbose_name_plural': 'Estilos Musicais',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('duration', models.TimeField(verbose_name='Duração')),
                ('main', models.BooleanField(default=False, verbose_name='Principal?')),
                ('file', models.FileField(upload_to='', verbose_name='Arquivo')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição do Perfil')),
                ('image', models.ImageField(upload_to='', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Última Modificação')),
                ('contact', models.ManyToManyField(to='music.Contact', verbose_name='Contatos')),
                ('music_style', models.ManyToManyField(to='music.MusicStyle', verbose_name='Estilo Musical')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Musico',
                'verbose_name_plural': 'Musicos',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musician', verbose_name='Musico'),
        ),
    ]
