# Generated by Django 3.2.3 on 2021-07-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicstyle',
            name='slug',
            field=models.SlugField(default=None, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
