# Generated by Django 3.2.3 on 2021-07-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210706_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
