# Generated by Django 3.2.3 on 2021-07-09 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_musician_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='contact',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='music_style',
            new_name='music_styles',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='id',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='user',
        ),
        migrations.AddField(
            model_name='musician',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='musician',
            name='document_number',
            field=models.CharField(default=None, max_length=100, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='id_card',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identidade'),
        ),
        migrations.AddField(
            model_name='musician',
            name='name',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musician',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user'),
            preserve_default=False,
        ),
    ]
