# Generated by Django 3.2.3 on 2021-07-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210709_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='musician',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music.musician', verbose_name='Músico'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('kind', models.CharField(choices=[('FB', 'Facebook'), ('IS', 'Instagram'), ('TT', 'Twitter')], max_length=50, verbose_name='Tipo')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musician', verbose_name='Músico')),
            ],
            options={
                'verbose_name': 'Mídia Social',
                'verbose_name_plural': 'Mídias Sociais',
            },
        ),
    ]
