# Generated by Django 3.2.3 on 2021-07-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210720_1007'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='contact',
        #     name='musician',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.musician', verbose_name='Músico'),
        # ),
    ]
