# Generated by Django 3.2.3 on 2021-08-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_contact_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musician', verbose_name='Músico')),
            ],
        ),
    ]
