# Generated by Django 3.2.3 on 2021-08-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(default='profile_placeholder.png', upload_to='', verbose_name='Foto'),
        ),
    ]
