# Generated by Django 3.2.3 on 2021-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210812_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='images/covers/', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(default='profile_placeholder.png', upload_to='images/profile/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='music/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='song',
            name='main',
            field=models.BooleanField(default=False, null=True, verbose_name='Principal?'),
        ),
    ]
