# Generated by Django 3.2.3 on 2021-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20210817_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Ordem'),
            preserve_default=False,
        ),
    ]
