# Generated by Django 3.2.3 on 2021-08-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_song_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
