# Generated by Django 3.2.3 on 2021-09-28 15:31

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_album_slug'),
    ]

    operations = [
        UnaccentExtension()
    ]
