# Generated by Django 3.2.3 on 2021-10-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20210928_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='id_card',
        ),
    ]
