# Generated by Django 3.2.3 on 2021-10-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_musician_artistic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/', verbose_name='Mídia (Ex: Vídeo ou áudio)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musician',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Perfil'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='music_styles',
            field=models.ManyToManyField(blank=True, to='music.MusicStyle', verbose_name='Estilo Musical'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
    ]
