# Generated by Django 3.2.3 on 2021-10-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20211013_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Álbum', 'verbose_name_plural': 'Álbuns'},
        ),
    ]
