# Generated by Django 3.2.3 on 2021-11-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_album_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2000-01-01 01:01:01", verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Última Modificação'),
        ),
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 01:01:01', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Última Modificação'),
        ),
        migrations.AlterField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Última Modificação'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Última Modificação'),
        ),
        migrations.AlterField(
            model_name='musicstyle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Última Modificação'),
        ),
    ]
