# Generated by Django 3.2.3 on 2021-11-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20211119_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicstyle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='musicstyle',
            name='updated_at',
        ),
    ]
