# Generated by Django 3.2.3 on 2021-12-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_remove_post_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created_at'], 'verbose_name': 'Álbum', 'verbose_name_plural': 'Álbuns'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created_at'], 'verbose_name': 'Música', 'verbose_name_plural': 'Músicas'},
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='images/covers/cover_placeholder.jpg', upload_to='images/covers/', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(default='images/profile/profile_placeholder.png', upload_to='images/profile/', verbose_name='Foto'),
        ),
    ]
