# Generated by Django 3.2.3 on 2021-07-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210702_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
