# Generated by Django 3.2.3 on 2021-07-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ddd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
    ]
